-- PostgreSQL schema for Zen'd Out. Run with a migration tool or psql.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (user_id varchar(36) PRIMARY KEY, username varchar(32) NOT NULL UNIQUE, email varchar(320) NOT NULL UNIQUE, password_hash varchar(255) NOT NULL, account_status varchar(20) NOT NULL DEFAULT 'pending', is_verified boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), last_login timestamptz);
CREATE TABLE IF NOT EXISTS profiles (profile_id varchar(36) PRIMARY KEY, user_id varchar(36) NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE, display_name varchar(80), bio varchar(500), avatar_url varchar(500), date_of_birth date, gender varchar(40), theme_preference varchar(20) DEFAULT 'light');
CREATE TABLE IF NOT EXISTS roles (role_id varchar(36) PRIMARY KEY, role_name varchar(80) NOT NULL UNIQUE, description varchar(255));
CREATE TABLE IF NOT EXISTS permissions (permission_id varchar(36) PRIMARY KEY, permission_name varchar(100) NOT NULL UNIQUE, description varchar(255));
CREATE TABLE IF NOT EXISTS role_permissions (role_permission_id varchar(36) PRIMARY KEY, role_id varchar(36) NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE, permission_id varchar(36) NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE, UNIQUE(role_id, permission_id));
CREATE TABLE IF NOT EXISTS user_roles (user_role_id varchar(36) PRIMARY KEY, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, role_id varchar(36) NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE, assigned_date timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, role_id));
CREATE TABLE IF NOT EXISTS journals (journal_id varchar(36) PRIMARY KEY, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, title varchar(200) NOT NULL, content text NOT NULL DEFAULT '', visibility varchar(20) NOT NULL DEFAULT 'private', mood_summary varchar(120), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mood_entries (mood_entry_id varchar(36) PRIMARY KEY, journal_id varchar(36) NOT NULL REFERENCES journals(journal_id) ON DELETE CASCADE, emotion varchar(80) NOT NULL, stress_level int CHECK(stress_level BETWEEN 0 AND 10), energy_level int CHECK(energy_level BETWEEN 0 AND 10), sleep_hours numeric(4,1), productivity_score int CHECK(productivity_score BETWEEN 0 AND 100), entry_date date NOT NULL);
CREATE TABLE IF NOT EXISTS follows (follow_id varchar(36) PRIMARY KEY, follower_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, following_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, followed_at timestamptz NOT NULL DEFAULT now(), UNIQUE(follower_id, following_id), CHECK(follower_id <> following_id));
CREATE TABLE IF NOT EXISTS posts (post_id varchar(36) PRIMARY KEY, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, journal_id varchar(36) REFERENCES journals(journal_id) ON DELETE SET NULL, caption text, visibility varchar(20) NOT NULL DEFAULT 'public', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS comments (comment_id varchar(36) PRIMARY KEY, post_id varchar(36) NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, comment_text text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS likes (like_id varchar(36) PRIMARY KEY, post_id varchar(36) NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, liked_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id, user_id));
CREATE TABLE IF NOT EXISTS notifications (notification_id varchar(36) PRIMARY KEY, sender_id varchar(36) REFERENCES users(user_id) ON DELETE SET NULL, receiver_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, notification_type varchar(50) NOT NULL, message varchar(500) NOT NULL, is_read boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS login_sessions (session_id varchar(36) PRIMARY KEY, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, login_time timestamptz NOT NULL DEFAULT now(), logout_time timestamptz, device varchar(255), browser varchar(255), ip_address inet);
CREATE TABLE IF NOT EXISTS reports (report_id varchar(36) PRIMARY KEY, reported_by varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, post_id varchar(36) NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE, reason varchar(500) NOT NULL, status varchar(30) NOT NULL DEFAULT 'open', reported_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS habits (habit_id varchar(36) PRIMARY KEY, habit_name varchar(120) NOT NULL, description varchar(500), target_frequency varchar(50));
CREATE TABLE IF NOT EXISTS habit_logs (habit_log_id varchar(36) PRIMARY KEY, habit_id varchar(36) NOT NULL REFERENCES habits(habit_id) ON DELETE CASCADE, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, completion_status varchar(30) NOT NULL, completion_percentage int CHECK(completion_percentage BETWEEN 0 AND 100), entry_date date NOT NULL);
CREATE TABLE IF NOT EXISTS challenges (challenge_id varchar(36) PRIMARY KEY, title varchar(160) NOT NULL, description text, duration_days int, reward_points int);
CREATE TABLE IF NOT EXISTS user_challenges (user_challenge_id varchar(36) PRIMARY KEY, challenge_id varchar(36) NOT NULL REFERENCES challenges(challenge_id) ON DELETE CASCADE, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, progress int NOT NULL DEFAULT 0, completion_status varchar(30) NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS puzzles (puzzle_id varchar(36) PRIMARY KEY, title varchar(160) NOT NULL, difficulty varchar(40), category varchar(80), max_score int);
CREATE TABLE IF NOT EXISTS puzzle_attempts (attempt_id varchar(36) PRIMARY KEY, puzzle_id varchar(36) NOT NULL REFERENCES puzzles(puzzle_id) ON DELETE CASCADE, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, score int, completion_time int, attempt_date timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS achievements (achievement_id varchar(36) PRIMARY KEY, title varchar(160) NOT NULL, badge varchar(120), description varchar(500), points int);
CREATE TABLE IF NOT EXISTS user_achievements (user_achievement_id varchar(36) PRIMARY KEY, achievement_id varchar(36) NOT NULL REFERENCES achievements(achievement_id) ON DELETE CASCADE, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, earned_date timestamptz NOT NULL DEFAULT now(), UNIQUE(achievement_id, user_id));
CREATE TABLE IF NOT EXISTS book_categories (category_id varchar(36) PRIMARY KEY, category_name varchar(120) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS books (book_id varchar(36) PRIMARY KEY, category_id varchar(36) REFERENCES book_categories(category_id) ON DELETE SET NULL, title varchar(255) NOT NULL, author varchar(255), publisher varchar(255), isbn varchar(32), description text);
CREATE TABLE IF NOT EXISTS user_library (library_id varchar(36) PRIMARY KEY, user_id varchar(36) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, book_id varchar(36) NOT NULL REFERENCES books(book_id) ON DELETE CASCADE, status varchar(30), reading_progress int CHECK(reading_progress BETWEEN 0 AND 100), rating int CHECK(rating BETWEEN 0 AND 5), date_added timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, book_id));
